### ISSUE TITLE
Formatting not working correctly with undefined and boolean values

### ISSUE THREAD

**Issue by drahgon55** [enoex/Bragi-Node#5]
```javascript
logger.log("debug","%s %s", undefined,true)
```

This produces the following output:
`true %s`

I would expect the out to be:
`undefined true`

**Comment by enoex** [comment]
Good catch! You're absolutely right, that should be expected (is also what util.format will output). Fixed in https://github.com/enoex/Bragi-Node/commit/5771b5e32303a4eeff967f08320c2cd053b58e74

**Comment by drahgon55** [comment]
awesome thanks for the quick response. Great library by the way

**Comment by drahgon55** [comment]
any chance of getting this new version on npm?

**Comment by enoex** [comment]
Thanks, I'm glad you're liking it. If you have any suggestions for improvements I'd love to hear them. 
New version is up on NPM @ version 0.0.23

**Comment by drahgon55** [comment]
Thanks. Where is the best place to send you a suggestion. Should I open a new ticket?

**Comment by enoex** [comment]
That'd be great - a new issue with an "enhancement" type (New Issue > click gear next to "Labels" and select enhancement)

**Comment by drahgon55** [comment]
Found another issue with the formatter when passing the integer zero to %s

```javascript
logger.log("debug","%s",0)
```
this outputs
`%s`

should output 
`0`
