### ISSUE TITLE
log with only a filter give undefined as a message

### ISSUE THREAD

**Issue by drahgon55** [enoex/Bragi-Node#7]
for instance in the below log you can see I just have a filter defined, there is no actual log message given. Bragi will give undefined as the log message. This always fools me into thinking I found some undefined variable in my code and I go searching for it. Only to find I did not add a log message. I think instead of undefined an empty string should be given so as to not be confusing.

bragi.log("startRoute:createMultipartUploadCB:verbose")

shows:
[  startRoute:createMultipartUploadCB:verbose  ] 	undefined

**Comment by enoex** [comment]
Good catch, thanks! It will no longer print 'undefined' if nothing is passed in for the second parameter (and instead use an empty string). Fixed in https://github.com/enoex/Bragi-Node/releases/tag/v0.1.2
